import { Product } from './types';

export const ALL_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Torta de Chocolate Intenso',
    description: 'Una porción generosa de torta de chocolate húmeda con varias capas de fudge cremoso. Ideal para los amantes del dulce y el cacao.',
    price: 8.50,
    restaurant: 'Dulce Paraíso',
    prepTime: 15,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?q=80&w=800&auto=format&fit=crop',
    category: 'Dulce',
  },
  {
    id: 2,
    name: 'Cheesecake de Frutos Rojos',
    description: 'Cremoso cheesecake sobre una base de galleta, cubierto con una salsa casera de fresas, arándanos y frambuesas. Un postre dulce y refrescante.',
    price: 9.00,
    restaurant: 'Repostería de la Abuela',
    prepTime: 20,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1567327683935-95495511a1b1?q=80&w=800&auto=format&fit=crop',
    category: 'Dulce',
  },
  {
    id: 3,
    name: 'Picada "Amigos y Sabores"',
    description: 'Una tabla abundante con una selección de quesos artesanales, fiambres de primera, aceitunas marinadas, pan casero y dips. Perfecta para compartir en una reunión o para una noche de picoteo salado.',
    price: 25.00,
    restaurant: 'El Bodegón',
    prepTime: 30,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1625944230944-192acff888d4?q=80&w=800&auto=format&fit=crop',
    category: 'Salado',
  },
  {
    id: 4,
    name: 'Hamburguesa Clásica con Papas',
    description: 'Jugosa hamburguesa de carne de res con lechuga, tomate, queso cheddar y salsa especial en pan brioche. Acompañada de papas fritas crujientes. Un plato salado que nunca falla.',
    price: 15.00,
    restaurant: 'Burger Joint',
    prepTime: 25,
    rating: 4.6,
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800&auto=format&fit=crop',
    category: 'Salado',
  },
  {
    id: 5,
    name: 'Ensalada César con Pollo',
    description: 'Pechuga de pollo a la parrilla sobre una cama de lechuga romana fresca, crutones, queso parmesano y aderezo César ligero. Una opción saludable, deliciosa y baja en calorías.',
    price: 12.50,
    restaurant: 'Verde y Fresco',
    prepTime: 20,
    rating: 4.5,
    imageUrl: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?q=80&w=800&auto=format&fit=crop',
    category: 'Bajas Calorías',
  },
  {
    id: 6,
    name: 'Bowl de Quinoa y Vegetales',
    description: 'Una base de quinoa nutritiva con brócoli, pimientos, zanahorias y calabacín asados, aderezado con una vinagreta de limón y hierbas. Comida baja en calorías y llena de sabor.',
    price: 13.00,
    restaurant: 'Verde y Fresco',
    prepTime: 25,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800&auto=format&fit=crop',
    category: 'Bajas Calorías',
  },
  {
    id: 7,
    name: 'Parrillada para Dos',
    description: 'Un festín de asado para compartir. Incluye tira de asado, vacío, chorizo, morcilla y pollo a la parrilla, acompañado de papas fritas y ensalada mixta. El auténtico sabor del asado argentino.',
    price: 45.00,
    restaurant: 'Fuegos del Sur',
    prepTime: 50,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?q=80&w=800&auto=format&fit=crop',
    category: 'Asado',
  },
  {
    id: 8,
    name: 'Provoleta a la Parrilla',
    description: 'Queso provolone derretido a la parrilla con orégano y aceite de oliva, servido con tomates cherry confitados y pan tostado. Una entrada perfecta para un asado.',
    price: 10.00,
    restaurant: 'Fuegos del Sur',
    prepTime: 15,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1604323990536-e54b24270813?q=80&w=800&auto=format&fit=crop',
    category: 'Asado',
  },
  {
    id: 9,
    name: 'Tacos al Pastor',
    description: 'Tres tortillas de maíz con carne de cerdo marinada en achiote, cocinada en trompo. Se sirve con piña, cebolla y cilantro. Un clásico salado y picante de la comida mexicana.',
    price: 11.00,
    restaurant: 'La Taquería',
    prepTime: 20,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?q=80&w=800&auto=format&fit=crop',
    category: 'Salado',
  },
  {
    id: 10,
    name: 'Wok de Pollo y Vegetales Thai',
    description: 'Trozos de pollo salteados con vegetales frescos en una salsa de curry y leche de coco. Bajo en calorías pero alto en sabor exótico.',
    price: 14.50,
    restaurant: 'Sabores de Asia',
    prepTime: 25,
    rating: 4.6,
    imageUrl: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?q=80&w=800&auto=format&fit=crop',
    category: 'Bajas Calorías',
  }
];